<?php

return [
    '
{
  "version": "1.0",
  "exported_at": "2026-06-15T12:06:02+00:00",
  "datasets": [
    {
      "name": "Tool Calling Reliability",
      "description": "Generate realistic tool-calling scenarios to improve function selection and argument accuracy.",
      "system_prompt": "Generate realistic user requests requiring the correct tool selection and valid arguments. Include ambiguity, edge cases, and difficult scenarios.",
      "schema": {
        "user_request": "string",
        "available_tools": [
          {
            "name": "string",
            "description": "string"
          }
        ],
        "expected_tool": "string",
        "expected_arguments": "object",
        "reasoning": "string"
      },
      "record_count": 100,
      "chunk_size": 10,
      "model": "openai/gpt-4.1-mini",
      "temperature": 0.8,
      "max_tokens": 2048,
      "strategy": "generic",
      "diversity_dimensions": [
        "domain",
        "difficulty",
        "ambiguity"
      ],
      "generation_seed": null,
      "uniqueness_level": "aggressive",
      "semantic_deduplication_enabled": true,
      "semantic_similarity_threshold": 0.9,
      "replacement_generation_enabled": true,
      "evaluation_enabled": true,
      "evaluation_model": "openai/gpt-4.1-mini",
      "minimum_quality_score": 80,
      "critic_enabled": true,
      "critic_model": "openai/gpt-4.1-mini",
      "refiner_enabled": true,
      "refiner_model": "openai/gpt-4.1-mini",
      "negative_example_ratio": 0.2,
      "conversation_enabled": true,
      "min_turns": 2,
      "max_turns": 4,
      "branching_enabled": false,
      "conversation_type": "assistant_chat",
      "augmentation_enabled": false,
      "augmentation_mode": "similar",
      "augmentation_strength": 0.5,
      "augmentation_target_count": null,
      "augmentation_expand_percent": null
    },
    {
      "name": "Customer Support Conversations",
      "description": "Generate realistic multi-turn customer support conversations.",
      "system_prompt": "Generate realistic customer support scenarios across different industries, customer moods, and problem types.",
      "schema": {
        "customer_problem": "string",
        "conversation": "array",
        "resolution_status": "string",
        "sentiment": "string"
      },
      "record_count": 100,
      "chunk_size": 10,
      "model": "openai/gpt-4.1-mini",
      "temperature": 0.7,
      "max_tokens": 2048,
      "strategy": "generic",
      "diversity_dimensions": [
        "industry",
        "tone",
        "difficulty"
      ],
      "generation_seed": null,
      "uniqueness_level": "balanced",
      "semantic_deduplication_enabled": true,
      "semantic_similarity_threshold": 0.92,
      "replacement_generation_enabled": true,
      "evaluation_enabled": true,
      "evaluation_model": "openai/gpt-4.1-mini",
      "minimum_quality_score": 75,
      "critic_enabled": true,
      "critic_model": "openai/gpt-4.1-mini",
      "refiner_enabled": true,
      "refiner_model": "openai/gpt-4.1-mini",
      "negative_example_ratio": 0.15,
      "conversation_enabled": true,
      "min_turns": 4,
      "max_turns": 8,
      "branching_enabled": false,
      "conversation_type": "assistant_chat",
      "augmentation_enabled": false,
      "augmentation_mode": "similar",
      "augmentation_strength": 0.5,
      "augmentation_target_count": null,
      "augmentation_expand_percent": null
    },
    {
      "name": "Business Workflow Scenarios",
      "description": "Generate structured business situations and decision-making workflows.",
      "system_prompt": "Generate realistic business scenarios involving operational, financial, HR, logistics, and management decisions.",
      "schema": {
        "scenario": "string",
        "department": "string",
        "problem": "string",
        "recommended_action": "string",
        "risk_level": "integer"
      },
      "record_count": 100,
      "chunk_size": 10,
      "model": "openai/gpt-4.1-mini",
      "temperature": 0.75,
      "max_tokens": 2048,
      "strategy": "generic",
      "diversity_dimensions": [
        "industry",
        "company_size",
        "complexity"
      ],
      "generation_seed": null,
      "uniqueness_level": "high",
      "semantic_deduplication_enabled": true,
      "semantic_similarity_threshold": 0.9,
      "replacement_generation_enabled": true,
      "evaluation_enabled": true,
      "evaluation_model": "openai/gpt-4.1-mini",
      "minimum_quality_score": 75,
      "critic_enabled": true,
      "critic_model": "openai/gpt-4.1-mini",
      "refiner_enabled": true,
      "refiner_model": "openai/gpt-4.1-mini",
      "negative_example_ratio": 0.1,
      "conversation_enabled": false,
      "min_turns": 2,
      "max_turns": 6,
      "branching_enabled": false,
      "conversation_type": "assistant_chat",
      "augmentation_enabled": false,
      "augmentation_mode": "similar",
      "augmentation_strength": 0.5,
      "augmentation_target_count": null,
      "augmentation_expand_percent": null
    },
    {
      "name": "Text Classification Dataset",
      "description": "Generate labeled text examples for classification tasks.",
      "system_prompt": "Generate realistic labeled text examples across multiple categories and ambiguity levels.",
      "schema": {
        "text": "string",
        "category": "string",
        "confidence": "number",
        "reasoning": "string"
      },
      "record_count": 100,
      "chunk_size": 10,
      "model": "openai/gpt-4.1-mini",
      "temperature": 0.6,
      "max_tokens": 2048,
      "strategy": "generic",
      "diversity_dimensions": [
        "domain",
        "difficulty"
      ],
      "generation_seed": null,
      "uniqueness_level": "balanced",
      "semantic_deduplication_enabled": true,
      "semantic_similarity_threshold": 0.92,
      "replacement_generation_enabled": true,
      "evaluation_enabled": true,
      "evaluation_model": "openai/gpt-4.1-mini",
      "minimum_quality_score": 75,
      "critic_enabled": true,
      "critic_model": "openai/gpt-4.1-mini",
      "refiner_enabled": false,
      "refiner_model": null,
      "negative_example_ratio": 0.25,
      "conversation_enabled": false,
      "min_turns": 2,
      "max_turns": 6,
      "branching_enabled": false,
      "conversation_type": "assistant_chat",
      "augmentation_enabled": false,
      "augmentation_mode": "similar",
      "augmentation_strength": 0.5,
      "augmentation_target_count": null,
      "augmentation_expand_percent": null
    },
    {
      "name": "Adversarial Edge Cases",
      "description": "Generate difficult and adversarial examples to stress-test models.",
      "system_prompt": "Generate edge cases, adversarial prompts, ambiguities, misleading requests, and difficult situations.",
      "schema": {
        "scenario": "string",
        "challenge_type": "string",
        "expected_behavior": "string",
        "difficulty_score": "integer"
      },
      "record_count": 100,
      "chunk_size": 10,
      "model": "openai/gpt-4.1-mini",
      "temperature": 0.9,
      "max_tokens": 2048,
      "strategy": "generic",
      "diversity_dimensions": [
        "difficulty",
        "failure_mode",
        "ambiguity"
      ],
      "generation_seed": null,
      "uniqueness_level": "aggressive",
      "semantic_deduplication_enabled": true,
      "semantic_similarity_threshold": 0.88,
      "replacement_generation_enabled": true,
      "evaluation_enabled": true,
      "evaluation_model": "openai/gpt-4.1-mini",
      "minimum_quality_score": 80,
      "critic_enabled": true,
      "critic_model": "openai/gpt-4.1-mini",
      "refiner_enabled": true,
      "refiner_model": "openai/gpt-4.1-mini",
      "negative_example_ratio": 0.4,
      "conversation_enabled": false,
      "min_turns": 2,
      "max_turns": 6,
      "branching_enabled": false,
      "conversation_type": "assistant_chat",
      "augmentation_enabled": false,
      "augmentation_mode": "similar",
      "augmentation_strength": 0.5,
      "augmentation_target_count": null,
      "augmentation_expand_percent": null
    },
    {
      "name": "Real Case Augmentation",
      "description": "Expand and diversify uploaded real-world examples.",
      "system_prompt": "Generate realistic variations of uploaded examples while preserving structure and intent.",
      "schema": {
        "input_case": "string",
        "augmented_version": "string",
        "variation_type": "string"
      },
      "record_count": 50,
      "chunk_size": 5,
      "model": "openai/gpt-4.1-mini",
      "temperature": 0.7,
      "max_tokens": 2048,
      "strategy": "generic",
      "diversity_dimensions": [
        "variation",
        "complexity"
      ],
      "generation_seed": null,
      "uniqueness_level": "balanced",
      "semantic_deduplication_enabled": true,
      "semantic_similarity_threshold": 0.92,
      "replacement_generation_enabled": true,
      "evaluation_enabled": true,
      "evaluation_model": "openai/gpt-4.1-mini",
      "minimum_quality_score": 75,
      "critic_enabled": true,
      "critic_model": "openai/gpt-4.1-mini",
      "refiner_enabled": true,
      "refiner_model": "openai/gpt-4.1-mini",
      "negative_example_ratio": 0,
      "conversation_enabled": false,
      "min_turns": 2,
      "max_turns": 6,
      "branching_enabled": false,
      "conversation_type": "assistant_chat",
      "augmentation_enabled": true,
      "augmentation_mode": "similar",
      "augmentation_strength": 0.7,
      "augmentation_target_count": null,
      "augmentation_expand_percent": 300
    }
  ]
}',
];
